# Generated by muraw.engines.tools.gen_ops — do not edit.
# EngineOp callables + OPS_BY_NAME from engines/catalog/ops.yaml.
from __future__ import annotations

import json

from . import graph
from .graph import EngineOp, OpMeta

add_scalar = EngineOp(
    meta=OpMeta(name='add_scalar', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "value",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

sub_scalar = EngineOp(
    meta=OpMeta(name='sub_scalar', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "value",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "reverse",
    "optional": true,
    "type": "bool"
  }
]''')),
    _infer_meta=None,
)

mul_scalar = EngineOp(
    meta=OpMeta(name='mul_scalar', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "value",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

div_scalar = EngineOp(
    meta=OpMeta(name='div_scalar', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "value",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "reverse",
    "optional": true,
    "type": "bool"
  }
]''')),
    _infer_meta=None,
)

add = EngineOp(
    meta=OpMeta(name='add', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None, None),
    _n_inputs=2,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[]''')),
    _infer_meta=graph._out_meta_broadcast,
)

subtract = EngineOp(
    meta=OpMeta(name='subtract', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None, None),
    _n_inputs=2,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[]''')),
    _infer_meta=graph._out_meta_broadcast,
)

multiply = EngineOp(
    meta=OpMeta(name='multiply', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None, None),
    _n_inputs=2,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[]''')),
    _infer_meta=graph._out_meta_broadcast,
)

divide = EngineOp(
    meta=OpMeta(name='divide', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None, None),
    _n_inputs=2,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[]''')),
    _infer_meta=graph._out_meta_broadcast,
)

composite = EngineOp(
    meta=OpMeta(name='composite', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None, None),
    _n_inputs=2,
    _variable_input=True,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "tops",
    "type": "i32_array"
  },
  {
    "count": 0,
    "key": "lefts",
    "type": "i32_array"
  },
  {
    "count": 0,
    "key": "dest_channels",
    "type": "i32_array"
  }
]''')),
    _infer_meta=None,
)

fill = EngineOp(
    meta=OpMeta(name='fill', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(),
    _n_inputs=0,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "value",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

ramp = EngineOp(
    meta=OpMeta(name='ramp', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(),
    _n_inputs=0,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "along",
    "type": "string",
    "values": [
      "columns",
      "rows"
    ]
  },
  {
    "count": 0,
    "key": "start",
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "step",
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "stop",
    "optional": true,
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

view = EngineOp(
    meta=OpMeta(name='view', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "width",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "height",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "reset_origin",
    "optional": true,
    "type": "bool"
  },
  {
    "count": 1,
    "key": "oob_valid",
    "optional": true,
    "type": "bool"
  },
  {
    "count": 0,
    "key": "src_channels",
    "optional": true,
    "type": "i32_array"
  },
  {
    "count": 1,
    "key": "row_step",
    "optional": true,
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_step",
    "optional": true,
    "type": "i32"
  }
]''')),
    _infer_meta=graph._out_meta_view,
)

pad = EngineOp(
    meta=OpMeta(name='pad', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "channel_before",
    "optional": true,
    "type": "i32"
  },
  {
    "count": 1,
    "key": "channel_after",
    "optional": true,
    "type": "i32"
  },
  {
    "count": 1,
    "key": "mode",
    "optional": true,
    "type": "string",
    "values": [
      "constant",
      "edge",
      "symmetric",
      "reflect"
    ]
  },
  {
    "count": 0,
    "key": "constant_values",
    "optional": true,
    "type": "f32_array"
  }
]''')),
    _infer_meta=graph._out_meta_pad,
)

tile = EngineOp(
    meta=OpMeta(name='tile', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "row_reps",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_reps",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "channel_reps",
    "type": "i32"
  }
]''')),
    _infer_meta=graph._out_meta_tile,
)

orientation = EngineOp(
    meta=OpMeta(name='orientation', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "orientation",
    "type": "i32"
  }
]''')),
    _infer_meta=graph._out_meta_orientation,
)

transpose = EngineOp(
    meta=OpMeta(name='transpose', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 3,
    "key": "axes",
    "type": "i32_array"
  }
]''')),
    _infer_meta=graph._out_meta_transpose,
)

cfa_bilinear_demosaic = EngineOp(
    meta=OpMeta(name='cfa_bilinear_demosaic', requires_2d=True, is_cfa=True, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_const(3),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "cfa_pattern",
    "type": "string"
  }
]''')),
    _infer_meta=None,
)

cfa_ea_demosaic = EngineOp(
    meta=OpMeta(name='cfa_ea_demosaic', requires_2d=True, is_cfa=True, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_const(3),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "cfa_pattern",
    "type": "string"
  },
  {
    "count": 1,
    "key": "fast",
    "optional": true,
    "type": "bool"
  }
]''')),
    _infer_meta=None,
)

matmul = EngineOp(
    meta=OpMeta(name='matmul', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_from_attr('columns'),
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "matrix",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "columns",
    "type": "i32"
  }
]''')),
    _infer_meta=None,
)

rgb_matrix_3x3 = EngineOp(
    meta=OpMeta(name='rgb_matrix_3x3', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 9,
    "key": "matrix",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

lut = EngineOp(
    meta=OpMeta(name='lut', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "lut",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

convert_dtype = EngineOp(
    meta=OpMeta(name='convert_dtype', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  },
  {
    "count": 1,
    "key": "src_bits",
    "optional": true,
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "optional": true,
    "type": "i32"
  },
  {
    "count": 1,
    "key": "clip_max",
    "optional": true,
    "type": "f32"
  }
]''')),
    _infer_meta=None,
)

cast_dtype = EngineOp(
    meta=OpMeta(name='cast_dtype', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  }
]''')),
    _infer_meta=None,
)

mono_lut = EngineOp(
    meta=OpMeta(name='mono_lut', requires_2d=False, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "lut",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "src_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  }
]''')),
    _infer_meta=None,
)

rgb_transform = EngineOp(
    meta=OpMeta(name='rgb_transform', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "input_lut",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 9,
    "key": "matrix",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "output_lut",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "src_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  },
  {
    "count": 1,
    "key": "hue_preserving",
    "type": "bool"
  }
]''')),
    _infer_meta=None,
)

rgb_clip_and_transform = EngineOp(
    meta=OpMeta(name='rgb_clip_and_transform', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 3,
    "key": "clip_max",
    "type": "f32_array"
  },
  {
    "count": 9,
    "key": "matrix",
    "type": "f32_array"
  }
]''')),
    _infer_meta=None,
)

cfa_normalize_raw = EngineOp(
    meta=OpMeta(name='cfa_normalize_raw', requires_2d=True, is_cfa=True, is_rgb=False),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "black_level",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "black_repeat_rows",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "black_repeat_cols",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "white_level",
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_h",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_v",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "linearization_table",
    "optional": true,
    "type": "i32_array"
  }
]''')),
    _infer_meta=None,
)

rgb_normalize_raw = EngineOp(
    meta=OpMeta(name='rgb_normalize_raw', requires_2d=True, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "black_level",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "black_repeat_rows",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "black_repeat_cols",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "white_level",
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_h",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_v",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "linearization_table",
    "optional": true,
    "type": "i32_array"
  }
]''')),
    _infer_meta=None,
)

rgb_apply_hue_sat_map = EngineOp(
    meta=OpMeta(name='rgb_apply_hue_sat_map', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "map_data",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "hue_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "sat_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "engine_opts",
    "optional": true,
    "type": "string"
  }
]''')),
    _infer_meta=None,
)

rgb_apply_hue_sat_val_map = EngineOp(
    meta=OpMeta(name='rgb_apply_hue_sat_val_map', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "map_data",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "hue_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "sat_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "val_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "engine_opts",
    "optional": true,
    "type": "string"
  }
]''')),
    _infer_meta=None,
)

rgb_apply_profile_gain_table_map = EngineOp(
    meta=OpMeta(name='rgb_apply_profile_gain_table_map', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gains",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "num_table_points",
    "type": "i32"
  },
  {
    "count": 5,
    "key": "weights",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "gamma",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "exposure_weight_gain",
    "type": "f32"
  }
]''')),
    _infer_meta=None,
)

fix_vignette = EngineOp(
    meta=OpMeta(name='fix_vignette', requires_2d=True, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "params",
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "center_x",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "center_y",
    "type": "f64"
  }
]''')),
    _infer_meta=None,
)

warp_rectilinear = EngineOp(
    meta=OpMeta(name='warp_rectilinear', requires_2d=True, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "radial_params",
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_coeffs",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "tangential_params",
    "optional": true,
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "center_x",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "center_y",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "use_bicubic",
    "type": "bool"
  }
]''')),
    _infer_meta=None,
)

rgb_apply_gain_map = EngineOp(
    meta=OpMeta(name='rgb_apply_gain_map', requires_2d=False, is_cfa=False, is_rgb=True),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=(3,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_values",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "map_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "start_plane",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f64"
  }
]''')),
    _infer_meta=None,
)

cfa_apply_gain_map = EngineOp(
    meta=OpMeta(name='cfa_apply_gain_map', requires_2d=True, is_cfa=True, is_rgb=False),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_values",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "map_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f64"
  }
]''')),
    _infer_meta=None,
)

apply_flat_gain_map = EngineOp(
    meta=OpMeta(name='apply_flat_gain_map', requires_2d=True, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_map",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "gain_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "gain_w",
    "type": "i32"
  }
]''')),
    _infer_meta=None,
)

map_polynomial = EngineOp(
    meta=OpMeta(name='map_polynomial', requires_2d=True, is_cfa=False, is_rgb=False),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=(None,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "start_plane",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "coefficients",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "degree",
    "type": "i32"
  }
]''')),
    _infer_meta=None,
)

cfa_fix_bad_pixels_constant = EngineOp(
    meta=OpMeta(name='cfa_fix_bad_pixels_constant', requires_2d=True, is_cfa=True, is_rgb=False),
    _out_dtype=graph._out_dtype_const('uint16'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=(1,),
    _n_inputs=1,
    _variable_input=False,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "constant",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bayer_phase",
    "type": "i32"
  }
]''')),
    _infer_meta=None,
)

OPS_BY_NAME = {
    'add_scalar': add_scalar,
    'sub_scalar': sub_scalar,
    'mul_scalar': mul_scalar,
    'div_scalar': div_scalar,
    'add': add,
    'subtract': subtract,
    'multiply': multiply,
    'divide': divide,
    'composite': composite,
    'fill': fill,
    'ramp': ramp,
    'view': view,
    'pad': pad,
    'tile': tile,
    'orientation': orientation,
    'transpose': transpose,
    'cfa_bilinear_demosaic': cfa_bilinear_demosaic,
    'cfa_ea_demosaic': cfa_ea_demosaic,
    'matmul': matmul,
    'rgb_matrix_3x3': rgb_matrix_3x3,
    'lut': lut,
    'convert_dtype': convert_dtype,
    'cast_dtype': cast_dtype,
    'mono_lut': mono_lut,
    'rgb_transform': rgb_transform,
    'rgb_clip_and_transform': rgb_clip_and_transform,
    'cfa_normalize_raw': cfa_normalize_raw,
    'rgb_normalize_raw': rgb_normalize_raw,
    'rgb_apply_hue_sat_map': rgb_apply_hue_sat_map,
    'rgb_apply_hue_sat_val_map': rgb_apply_hue_sat_val_map,
    'rgb_apply_profile_gain_table_map': rgb_apply_profile_gain_table_map,
    'fix_vignette': fix_vignette,
    'warp_rectilinear': warp_rectilinear,
    'rgb_apply_gain_map': rgb_apply_gain_map,
    'cfa_apply_gain_map': cfa_apply_gain_map,
    'apply_flat_gain_map': apply_flat_gain_map,
    'map_polynomial': map_polynomial,
    'cfa_fix_bad_pixels_constant': cfa_fix_bad_pixels_constant,
}

__all__ = [
    'OPS_BY_NAME',
    'add',
    'add_scalar',
    'apply_flat_gain_map',
    'cast_dtype',
    'cfa_apply_gain_map',
    'cfa_bilinear_demosaic',
    'cfa_ea_demosaic',
    'cfa_fix_bad_pixels_constant',
    'cfa_normalize_raw',
    'composite',
    'convert_dtype',
    'div_scalar',
    'divide',
    'fill',
    'fix_vignette',
    'lut',
    'map_polynomial',
    'matmul',
    'mono_lut',
    'mul_scalar',
    'multiply',
    'orientation',
    'pad',
    'ramp',
    'rgb_apply_gain_map',
    'rgb_apply_hue_sat_map',
    'rgb_apply_hue_sat_val_map',
    'rgb_apply_profile_gain_table_map',
    'rgb_clip_and_transform',
    'rgb_matrix_3x3',
    'rgb_normalize_raw',
    'rgb_transform',
    'sub_scalar',
    'subtract',
    'tile',
    'transpose',
    'view',
    'warp_rectilinear',
]
