# Generated by mu-image-engine/tools/gen_op_catalog.py — do not edit.
# Typed wrappers + OPS_CATALOG schema from catalog/ops.yaml.
from __future__ import annotations

from typing import Any

from . import mc
from .mc import Tensor

OPS_CATALOG = {
  "ops": {
    "bilinear_demosaic": {
      "attrs": [
        {
          "count": 1,
          "key": "cfa_pattern",
          "type": "string"
        }
      ],
      "inputs": [
        {
          "channels": 1
        }
      ],
      "outputs": [
        {
          "channels": 3
        }
      ]
    },
    "lut": {
      "attrs": [
        {
          "count": 0,
          "key": "lut",
          "type": "f32_array"
        }
      ],
      "inputs": [
        {
          "channels": "any"
        }
      ],
      "outputs": [
        {
          "channels": "same"
        }
      ]
    },
    "matrix": {
      "attrs": [
        {
          "count": 9,
          "key": "matrix",
          "type": "f32_array"
        }
      ],
      "inputs": [
        {
          "channels": 3
        }
      ],
      "outputs": [
        {
          "channels": "same"
        }
      ]
    },
    "mul_scalar": {
      "attrs": [
        {
          "count": 1,
          "key": "value",
          "type": "f32"
        }
      ],
      "inputs": [
        {
          "channels": "any"
        }
      ],
      "outputs": [
        {
          "channels": "same"
        }
      ]
    },
    "sub_scalar": {
      "attrs": [
        {
          "count": 1,
          "key": "value",
          "type": "f32"
        }
      ],
      "inputs": [
        {
          "channels": "any"
        }
      ],
      "outputs": [
        {
          "channels": "same"
        }
      ]
    }
  },
  "version": 1
}

def sub_scalar(x: Tensor, *, value: float) -> Tensor:
    """Engine op ``sub_scalar`` (from catalog/ops.yaml)."""
    return mc.op("sub_scalar", x, value=value)


def mul_scalar(x: Tensor, *, value: float) -> Tensor:
    """Engine op ``mul_scalar`` (from catalog/ops.yaml)."""
    return mc.op("mul_scalar", x, value=value)


def bilinear_demosaic(x: Tensor, *, cfa_pattern: str) -> Tensor:
    """Engine op ``bilinear_demosaic`` (from catalog/ops.yaml)."""
    return mc.op("bilinear_demosaic", x, cfa_pattern=cfa_pattern)


def matrix(x: Tensor, *, matrix: Any) -> Tensor:
    """Engine op ``matrix`` (from catalog/ops.yaml)."""
    return mc.op("matrix", x, matrix=matrix)


def lut(x: Tensor, *, lut: Any) -> Tensor:
    """Engine op ``lut`` (from catalog/ops.yaml)."""
    return mc.op("lut", x, lut=lut)

