# Generated by muimg.engines.tools.gen_ops — do not edit.
# EngineOp callables + OPS_BY_NAME from engines/catalog/ops.yaml.
from __future__ import annotations

import json

from . import graph
from .graph import EngineOp, OpMeta

sub_scalar = EngineOp(
    meta=OpMeta(name='sub_scalar'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "value",
    "type": "f32"
  }
]''')),
)

mul_scalar = EngineOp(
    meta=OpMeta(name='mul_scalar'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "value",
    "type": "f32"
  }
]''')),
)

bilinear_demosaic = EngineOp(
    meta=OpMeta(name='bilinear_demosaic'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_const(3),
    _in_channels=1,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "cfa_pattern",
    "type": "string"
  }
]''')),
)

matrix = EngineOp(
    meta=OpMeta(name='matrix'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 9,
    "key": "matrix",
    "type": "f32_array"
  }
]''')),
)

lut = EngineOp(
    meta=OpMeta(name='lut'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "lut",
    "type": "f32_array"
  }
]''')),
)

convert_dtype = EngineOp(
    meta=OpMeta(name='convert_dtype'),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  },
  {
    "count": 1,
    "key": "src_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "clip_max",
    "type": "f32"
  }
]''')),
)

mono_lut = EngineOp(
    meta=OpMeta(name='mono_lut'),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=1,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "lut",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "src_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  }
]''')),
)

transform_color = EngineOp(
    meta=OpMeta(name='transform_color'),
    _out_dtype=graph._out_dtype_from_attr('dest_dtype'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "input_lut",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 9,
    "key": "matrix",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "output_lut",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "src_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dst_bits",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "dest_dtype",
    "type": "string"
  },
  {
    "count": 1,
    "key": "hue_preserving",
    "type": "bool"
  }
]''')),
)

clip_and_transform_color = EngineOp(
    meta=OpMeta(name='clip_and_transform_color'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 3,
    "key": "clip_max",
    "type": "f32_array"
  },
  {
    "count": 9,
    "key": "matrix",
    "type": "f32_array"
  }
]''')),
)

normalize_raw = EngineOp(
    meta=OpMeta(name='normalize_raw'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "black_level",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "black_repeat_rows",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "black_repeat_cols",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "samples_per_pixel",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "white_level",
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_h",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "black_delta_v",
    "optional": true,
    "type": "f32_array"
  },
  {
    "count": 0,
    "key": "linearization_table",
    "optional": true,
    "type": "i32_array"
  }
]''')),
)

apply_hue_sat_map = EngineOp(
    meta=OpMeta(name='apply_hue_sat_map'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "map_data",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "hue_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "sat_divs",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "val_divs",
    "type": "i32"
  }
]''')),
)

apply_exposure_ramp = EngineOp(
    meta=OpMeta(name='apply_exposure_ramp'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "white",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "black",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "min_black",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "support_overrange",
    "type": "bool"
  }
]''')),
)

apply_profile_gain_table_map = EngineOp(
    meta=OpMeta(name='apply_profile_gain_table_map'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gains",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "num_table_points",
    "type": "i32"
  },
  {
    "count": 5,
    "key": "weights",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "gamma",
    "type": "f32"
  },
  {
    "count": 1,
    "key": "exposure_weight_gain",
    "type": "f32"
  }
]''')),
)

fix_vignette = EngineOp(
    meta=OpMeta(name='fix_vignette'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "params",
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "center_x",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "center_y",
    "type": "f64"
  }
]''')),
)

warp_rectilinear = EngineOp(
    meta=OpMeta(name='warp_rectilinear'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "radial_params",
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_coeffs",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "tangential_params",
    "optional": true,
    "type": "f64_array"
  },
  {
    "count": 1,
    "key": "center_x",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "center_y",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "use_bicubic",
    "type": "bool"
  }
]''')),
)

apply_gain_map = EngineOp(
    meta=OpMeta(name='apply_gain_map'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(3),
    _in_channels=3,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_values",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "map_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "start_plane",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f64"
  }
]''')),
)

apply_gain_map_cfa = EngineOp(
    meta=OpMeta(name='apply_gain_map_cfa'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=1,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_values",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "points_v",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "points_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "map_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "spacing_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "spacing_h",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_v",
    "type": "f64"
  },
  {
    "count": 1,
    "key": "origin_h",
    "type": "f64"
  }
]''')),
)

apply_flat_gain_map = EngineOp(
    meta=OpMeta(name='apply_flat_gain_map'),
    _out_dtype=graph._out_dtype_const('float32'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=1,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 0,
    "key": "gain_map",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "gain_h",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "gain_w",
    "type": "i32"
  }
]''')),
)

map_polynomial = EngineOp(
    meta=OpMeta(name='map_polynomial'),
    _out_dtype=graph._out_dtype_same,
    _out_channels=graph._out_channels_same,
    _in_channels=None,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "top",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "left",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bottom",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "right",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "start_plane",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "num_planes",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "row_pitch",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "col_pitch",
    "type": "i32"
  },
  {
    "count": 0,
    "key": "coefficients",
    "type": "f32_array"
  },
  {
    "count": 1,
    "key": "degree",
    "type": "i32"
  }
]''')),
)

fix_bad_pixels_constant = EngineOp(
    meta=OpMeta(name='fix_bad_pixels_constant'),
    _out_dtype=graph._out_dtype_const('uint16'),
    _out_channels=graph._out_channels_const(1),
    _in_channels=1,
    _attr_specs=tuple(json.loads(r'''[
  {
    "count": 1,
    "key": "constant",
    "type": "i32"
  },
  {
    "count": 1,
    "key": "bayer_phase",
    "type": "i32"
  }
]''')),
)

OPS_BY_NAME = {
    'sub_scalar': sub_scalar,
    'mul_scalar': mul_scalar,
    'bilinear_demosaic': bilinear_demosaic,
    'matrix': matrix,
    'lut': lut,
    'convert_dtype': convert_dtype,
    'mono_lut': mono_lut,
    'transform_color': transform_color,
    'clip_and_transform_color': clip_and_transform_color,
    'normalize_raw': normalize_raw,
    'apply_hue_sat_map': apply_hue_sat_map,
    'apply_exposure_ramp': apply_exposure_ramp,
    'apply_profile_gain_table_map': apply_profile_gain_table_map,
    'fix_vignette': fix_vignette,
    'warp_rectilinear': warp_rectilinear,
    'apply_gain_map': apply_gain_map,
    'apply_gain_map_cfa': apply_gain_map_cfa,
    'apply_flat_gain_map': apply_flat_gain_map,
    'map_polynomial': map_polynomial,
    'fix_bad_pixels_constant': fix_bad_pixels_constant,
}
